# Generated by Django 2.1 on 2018-09-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_sys', '0002_testnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
