# Generated by Django 2.1 on 2018-09-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_sys', '0006_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserAccountInfo',
        ),
    ]
